name: Azure deployment - Container Apps

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_REGISTRY_URL: ghcr.io
  AZURE_RESOURCE_GROUP: go-container-rg
  AZURE_CONTAINERAPP_NAME: go-backend-api
  AZURE_LOCATION: eastus
  CONTAINERAPPS_ENV: go-env

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_REGISTRY_URL }}/${{ github.repository }}:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp up \
            --name ${{ env.AZURE_CONTAINERAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --environment ${{ env.CONTAINERAPPS_ENV }} \
            --location ${{ env.AZURE_LOCATION }} \
            --ingress external \
            --target-port 8080 \
            --image ${{ env.IMAGE_REGISTRY_URL }}/${{ github.repository }}:latest \
            --registry-server ${{ env.IMAGE_REGISTRY_URL }} \
            --registry-username ${{ github.actor }} \
            --registry-password ${{ secrets.GITHUB_TOKEN }} \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
